(deftheme csd
  "Created 2014-07-06.")

(custom-theme-set-faces
 'csd
 '(default ((t (:family "Monospace" :foundry "default" :width normal :height 180 :weight bold :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "#000000" :stipple nil :inherit nil))))
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(minibuffer-prompt ((t (:foreground "#ffffff" :background "#000000"))))
 '(highlight ((t (:foreground "#111111" :background "#aaaaaa"))))
 '(region ((t (:foreground "#555555" :background "#aaaaaa"))))
 '(shadow ((t (:foreground "#aaffaa" :background "#000000"))))
 '(secondary-selection ((t (:foreground "#aaffaa" :background "#000000"))))
 '(trailing-whitespace ((t (:foreground "#aaffaa" :background "#aa0000"))))
 '(font-lock-builtin-face ((t (:foreground "#8cadde" :background "#000000"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#808080" :background "#000000"))))
 ;comment
 '(font-lock-comment-face ((t (:foreground "#808080" :background "#000000"))))
 '(font-lock-constant-face ((t (:foreground "#ff00ff" :background "#000000"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#ffffff" :background "#000000"))))
 '(font-lock-type-face ((t (:foreground "#eeaaaa" :background "#000000"))))
 '(font-lock-function ((t (:foreground "#ffffff" :background "#000000"))))
 '(font-lock-keyword-face ((t (:foreground "#8cadde" :background "#000000"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#00ee00" :background "#000000"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#00aaaa"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffffff"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(fringe ((t (:foreground "#e1a633"))))
 '(header-line ((t (:foreground "#ffffff" :background "#000000"))))
 '(mode-line ((t (:foreground "#333333" :background "#cccccc"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:foreground "#cccccc" :background "#333333"))))
 '(mode-line-inactive ((t (:foreground "#000000" :background "#808080"))))
 '(isearch ((t (:foreground "#ffffff" :background "#000000"))))
 '(isearch-fail ((t (:foreground "#b55059" :background "#000000"))))
 '(lazy-highlight ((t (:foreground "#fffeee" :background "#ff0111"))))
 '(match ((t (:foreground "#00ff00" :background "#aa00aa"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'csd)
